#!/usr/bin/env python3
#
# Purpose: Merge two accounts.tsv files
#

import argparse
import csv
import json
import os.path
import icpcpwutils
import yaml

parser = argparse.ArgumentParser(
    formatter_class=argparse.RawTextHelpFormatter,
    description='Merge two accounts.tsv files')
parser.add_argument('first_accounts_tsv', help='first accounts tsv file')
parser.add_argument('second_accounts_tsv', help='second accounts tsv file')
parser.add_argument('output_dir', help='Directory to store output files.')

args = parser.parse_args()

if not os.path.isdir(args.output_dir):
    print(f'{args.output_dir} is not an existing directory, creating...')
    os.makedirs(args.output_dir, exist_ok=True)

output_tsv_file  = f'{args.output_dir}/combined.accounts.tsv'
with open(output_tsv_file  ,'w') as outf:
   writer = csv.writer(outf, delimiter='\t')

   with open(args.first_accounts_tsv)  as fd:
       rd = csv.reader(fd, delimiter="\t", quotechar='"')
       for row in rd:
           writer.writerow(row)

   with open(args.second_accounts_tsv)  as fd:
       rd = csv.reader(fd, delimiter="\t", quotechar='"')
       for row in rd:
           if row[0] != 'accounts':
                writer.writerow(row)

print(f'combined accounts.tsv files were written to {output_tsv_file}')
