name: Samples
on: [push, pull_request]

jobs:
  run-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update apt cache
        run: sudo apt update
      - name: Install packages
        run: ./install.sh
      - name: Run all samples
        run: make all
        working-directory: sample

